
CREATE TABLE IF NOT EXISTS listings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    seller_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    cashback INT NOT NULL,
    category VARCHAR(100) NOT NULL,
    slots INT NOT NULL DEFAULT 1,
    description TEXT,
    status ENUM('PENDING','ACTIVE','REJECTED','ARCHIVED') DEFAULT 'PENDING',
    reason TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE deals ADD COLUMN listing_id INT NULL,
  ADD CONSTRAINT fk_deals_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE SET NULL;
